"""empty message

Revision ID: 4917325bdc9a
Revises: None
Create Date: 2016-02-09 13:40:47.531512

"""

# revision identifiers, used by Alembic.
revision = '4917325bdc9a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('host', sa.String(length=16), nullable=True),
    sa.Column('port', sa.String(length=6), nullable=True),
    sa.Column('db', sa.String(length=15), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('eportfolio_path', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=16), nullable=True),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_request', sa.DateTime(), nullable=True),
    sa.Column('requests_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('school')
    ### end Alembic commands ###
